permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 徐超 
  email: belikov_dr@163.com
  link: http://deeper-think.github.io
  github: http://github.com/deeper-think

# 站点信息
title: 徐超的博客 
description: 徐超的博客
url: http://deeper-think.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://7u2rbh.com1.z0.glb.clouddn.com/09-024458_765.jpg
favicon: http://7u2rbh.com1.z0.glb.clouddn.com/09-024458_765.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: deeper-think.github.io

# disqus 设置
disqus:
  shortname: xuchao-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - KVM
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
